###
GET http://localhost:4000/

######################################### Autentication #################################################

### register
POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "email": "shenhav.dafadi@gmail.com",
    "password": "123123",
    "name":"test"
}



### login
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "email": "hen.torgeman6@gmail.com",
    "password": "191919"
}



### logout
POST http://localhost:4000/auth/logout
Content-Type: application/json

{
    "message": "this is my new message",
    "sender": "Adi"
}



######################################### Posts #################################################

### get all posts
GET http://localhost:4000/post/allPosts
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyM2Y3ZTNjZDRmMDU2YTc2OTVjNDdkNiIsImlhdCI6MTY0ODU4NjE4NiwiZXhwIjoxNjQ4NTg5Nzg2fQ.AhcEjPPsBXEJJXgUaVnlwnDegUYFn0Whdz6BRFfOnAc



### get post by id
GET http://localhost:4000/post/621f52e6c9dde976ffe6308e



### add new post
POST http://localhost:4000/post/add
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyM2Y3ZTNjZDRmMDU2YTc2OTVjNDdkNiIsImlhdCI6MTY0ODU4NjE4NiwiZXhwIjoxNjQ4NTg5Nzg2fQ.AhcEjPPsBXEJJXgUaVnlwnDegUYFn0Whdz6BRFfOnAc
Content-Type: application/json

{
     "title":"Test add post (from api_calls)",
     "description": "post message test with Sender referance without Enum"
}



### edit post by id
POST http://localhost:4000/post/edit/6243677b85a4abf0ed378de1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyM2Y3ZTNjZDRmMDU2YTc2OTVjNDdkNiIsImlhdCI6MTY0ODU4NjE4NiwiZXhwIjoxNjQ4NTg5Nzg2fQ.AhcEjPPsBXEJJXgUaVnlwnDegUYFn0Whdz6BRFfOnAc
Content-Type: application/json

{
      "title":"Test edit post (from api_calls)",
     "description": "post message test with Sender referance without Enum"
}



### delete post by id
POST http://localhost:4000/post/delete/6243677b85a4abf0ed378de1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyM2Y3ZTNjZDRmMDU2YTc2OTVjNDdkNiIsImlhdCI6MTY0ODU4NjE4NiwiZXhwIjoxNjQ4NTg5Nzg2fQ.AhcEjPPsBXEJJXgUaVnlwnDegUYFn0Whdz6BRFfOnAc
Content-Type: application/json

{
      "title":"Test edit post (from api_calls)",
     "description": "post message test with Sender referance without Enum"
}



# ###
# GET http://localhost:4000/post/MyPost
# Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyM2Y3ZTNjZDRmMDU2YTc2OTVjNDdkNiIsImlhdCI6MTY0ODU4NjE4NiwiZXhwIjoxNjQ4NTg5Nzg2fQ.AhcEjPPsBXEJJXgUaVnlwnDegUYFn0Whdz6BRFfOnAc



###
GET http://localhost:4000/sos
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyM2Y3ZTNjZDRmMDU2YTc2OTVjNDdkNiIsImlhdCI6MTY0ODU4NjE4NiwiZXhwIjoxNjQ4NTg5Nzg2fQ.AhcEjPPsBXEJJXgUaVnlwnDegUYFn0Whdz6BRFfOnAc



###
POST http://localhost:4000/sos
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyM2Y3ZTNjZDRmMDU2YTc2OTVjNDdkNiIsImlhdCI6MTY0ODU4NjE4NiwiZXhwIjoxNjQ4NTg5Nzg2fQ.AhcEjPPsBXEJJXgUaVnlwnDegUYFn0Whdz6BRFfOnAc
Content-Type: application/json

{
     "title":"Test add sos post (from api_calls)",
     "message": "post message test with Sender referance without Enum",
     "freinds_circle": 1,
     "area": "Rishon",
     "address":"Nobel 3"    
}


######################################### Comments #################################################

###
GET http://localhost:4000/comment/624446495afc5403754eecfa/allComments
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDQyYWM4YmYyN2I0MGMzZDY2MDc1NCIsImlhdCI6MTY0ODY1OTgwOSwiZXhwIjoxNjQ4NjYzNDA5fQ.eKGOgt10uJa8RGpWKD-QtK9JRwMNDnm4dwYitY1Tku4



###
GET http://localhost:4000/comment/6241984af2302ba19ebefc53
# Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyM2Y3ZTNjZDRmMDU2YTc2OTVjNDdkNiIsImlhdCI6MTY0ODU4NjE4NiwiZXhwIjoxNjQ4NTg5Nzg2fQ.AhcEjPPsBXEJJXgUaVnlwnDegUYFn0Whdz6BRFfOnAc

