###
GET http://localhost:4000/

###
GET http://localhost:4000/post/allPosts
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzFmZjA5ZDZiZWZiNDJjNGE1NDY4MCIsImlhdCI6MTY0NzgyMzgwMCwiZXhwIjoxNjQ3ODI3NDAwfQ.KBukqZzoK90ww1ptC92hUz2_XvbfCLLZDkX78EH1reI

###
GET http://localhost:4000/sos
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzFmZjA5ZDZiZWZiNDJjNGE1NDY4MCIsImlhdCI6MTY0NzgyMzgwMCwiZXhwIjoxNjQ3ODI3NDAwfQ.KBukqZzoK90ww1ptC92hUz2_XvbfCLLZDkX78EH1reI


# ###
# GET http://localhost:4000/post/MyPost
# Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzFmZjA5ZDZiZWZiNDJjNGE1NDY4MCIsImlhdCI6MTY0NzgyMzgwMCwiZXhwIjoxNjQ3ODI3NDAwfQ.KBukqZzoK90ww1ptC92hUz2_XvbfCLLZDkX78EH1reI


###
GET http://localhost:4000/post/621f52e6c9dde976ffe6308e


###
POST http://localhost:4000/post/add
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzFmZjA5ZDZiZWZiNDJjNGE1NDY4MCIsImlhdCI6MTY0NzgyMzgwMCwiZXhwIjoxNjQ3ODI3NDAwfQ.KBukqZzoK90ww1ptC92hUz2_XvbfCLLZDkX78EH1reI
Content-Type: application/json

{

     "title":"Test post2",
     "description": "post message test with Sender referance without Enum"

}

###

POST http://localhost:4000/post/edit/6233068b875cdeee8be1bf29
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzFmZjA5ZDZiZWZiNDJjNGE1NDY4MCIsImlhdCI6MTY0NzgyMzgwMCwiZXhwIjoxNjQ3ODI3NDAwfQ.KBukqZzoK90ww1ptC92hUz2_XvbfCLLZDkX78EH1reI
Content-Type: application/json

{
     
      "title":"Test post2",
     "description": "post message test with Sender referance without Enum"

}


###
POST http://localhost:4000/sos
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzFmZjA5ZDZiZWZiNDJjNGE1NDY4MCIsImlhdCI6MTY0NzgyMzgwMCwiZXhwIjoxNjQ3ODI3NDAwfQ.KBukqZzoK90ww1ptC92hUz2_XvbfCLLZDkX78EH1reI
Content-Type: application/json

{

     "title":"Test post1",
     "message": "post message test with Sender referance without Enum",
     "freinds_circle": 1,
     "area": "Rishon",
     "address":"Nobel 3"    
   

}


###
POST http://localhost:4000/comment/62261457681cb76c1c8c1e11
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzFmZjA5ZDZiZWZiNDJjNGE1NDY4MCIsImlhdCI6MTY0NzgyMzgwMCwiZXhwIjoxNjQ3ODI3NDAwfQ.KBukqZzoK90ww1ptC92hUz2_XvbfCLLZDkX78EH1reI
Content-Type: application/json

{
     "message": "Comment to post Id : 62261457681cb76c1c8c1e11"
}


###
POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "email": "ortallik@gmail.com",
    "password": "123456",
    "name":"test"
}

###
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "email": "shenhav.dafadi@gmail.com",
    "password": "123123"
}


###
POST http://localhost:4000/auth/logout
Content-Type: application/json

{
    "message": "this is my new message",
    "sender": "Adi"
}

###
GET http://localhost:4000/comment/6241984af2302ba19ebefc53
# Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzFmZjA5ZDZiZWZiNDJjNGE1NDY4MCIsImlhdCI6MTY0NzgyMzgwMCwiZXhwIjoxNjQ3ODI3NDAwfQ.KBukqZzoK90ww1ptC92hUz2_XvbfCLLZDkX78EH1reI


